export const enum RoleKeys {
  ADMINISTRATOR = 'ADMINISTRATOR',
  SUPERUSER = 'SUPERUSER',
  OPERATOR = 'OPERATOR',
  VIEWER = 'VIEWER',
  MAINTAINER = 'MAINTAINER',
  PROJECTMANAGER = 'PROJECTMANAGER'
}
